name: 'My Own Action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  steps:
    - id: hello
      using: 'node16'
      main: 'hello.js'
    - name: 📋 Get release data
      id: release
      uses: actions/github-script@v6
      env:
        tag: '0'
        slack_description: 'slack'
      using: 'node16'
      main: 'realse-data.js'


