name: 'My Own Action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - id: hello
      uses: actions/github-script@v6
      with:
        script: |
          console.log(`Hello`);
          core.setOutput("hello", "here");
    - name: 📋 Get release data
      id: release
      uses: actions/github-script@v6
      env:
        tag: '0'
        slack_description: 'slack'
      with:
        script: |
          console.log(`release`);
          core.setOutput("release", "here");
    - name: goodbye
      id: goodbye
      run: node hello.js
      shell: bash


